apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garmin-grafana-datasource
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure
    kind: ClusterSecretStore
  target:
    name: garmin-grafana-datasource
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        INFLUXDB_USERNAME: "{{ .INFLUXDB_USERNAME }}"
        INFLUXDB_PASSWORD: "{{ .INFLUXDB_PASSWORD }}"
  data:
    - secretKey: INFLUXDB_USERNAME
      remoteRef:
        key: GARMIN-GRAFANA-INFLUXDB-USERNAME
    - secretKey: INFLUXDB_PASSWORD
      remoteRef:
        key: GARMIN-GRAFANA-INFLUXDB-PASSWORD
