apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"

  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: GRAFANA-ADMIN-USER

    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: GRAFANA-ADMIN-PASSWORD
