apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-exporter-config
  namespace: monitoring
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: pve-exporter-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        pve.yml: "{{ .config }}"

  data:
    - secretKey: config
      remoteRef:
        key: PROXMOX-PVE-EXPORTER-CONFIG
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: prometheus-additional-scrape-configs
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        pve.yaml: "{{ .config }}"

  data:
    - secretKey: config
      remoteRef:
        key: PROXMOX-PROMETHEUS-SCRAPE-CONFIG
