apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-credentials
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure
    kind: ClusterSecretStore
  target:
    name: n8n-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: N8N-ENCRYPTION-KEY
