apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
