apiVersion: batch/v1
kind: CronJob
metadata:
  name: obsidian-git-backup
  namespace: obsidian
spec:
  schedule: "0 * * * *"  # every hour
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: git-backup
              image: alpine/git:latest
              env:
                - name: GIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: git-credentials
                      key: GIT_TOKEN
                - name: GIT_AUTHOR_NAME
                  value: "obsidian-backup"
                - name: GIT_AUTHOR_EMAIL
                  value: "backup@local"
              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  echo "Installing dependencies..."
                  apk add --no-cache git rsync

                  echo "Cloning repo..."
                  git clone https://$GIT_TOKEN@github.com/andriusdalgeda/obsidian.git /repo

                  cd /repo

                  echo "Configuring git..."
                  git config user.name "obsidian-backup"
                  git config user.email "backup@local"

                  echo "Syncing vault only..."

                  rsync -a --delete \
                    --exclude='.cache' \
                    --exclude='.config' \
                    --exclude='.local' \
                    --exclude='.dbus' \
                    --exclude='.pki' \
                    --exclude='Desktop' \
                    --exclude='ssl' \
                    --exclude='.XDG' \
                    /data/ /repo/

                  echo "Staging changes..."
                  git add .

                  if git diff --cached --quiet; then
                    echo "No changes detected"
                    exit 0
                  fi

                  echo "Committing..."
                  git commit -m "Backup $(date +%F-%T)"

                  echo "Pushing..."
                  git push origin main

                  echo "Backup complete"
              volumeMounts:
                - name: obsidian-data
                  mountPath: /data
          volumes:
            - name: obsidian-data
              persistentVolumeClaim:
                claimName: obsidian-config