apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-config
  namespace: obsidian
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
