apiVersion: v1
kind: ServiceAccount
metadata:
  name: capacitor-next-preset-readonly
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capacitor-next-preset-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: capacitor-next-preset-readonly
    namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capacitor-impersonate-readonly
  namespace: flux-system
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    resourceNames:
      - capacitor-next-preset-readonly
    verbs:
      - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capacitor-impersonate-readonly
  namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capacitor-impersonate-readonly
subjects:
  - kind: ServiceAccount
    name: capacitor
    namespace: flux-system
