apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure
    kind: ClusterSecretStore
  target:
    name: capacitor-next
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        LICENSE_KEY: message laszlo at gimlet.io
        SESSION_HASH_KEY: "{{ .SESSION_HASH_KEY }}"
        SESSION_BLOCK_KEY: "{{ .SESSION_BLOCK_KEY }}"
        registry.yaml: |
          clusters:
            - id: in-cluster
              name: In-cluster
              apiServerURL: https://kubernetes.default.svc
              certificateAuthorityFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              serviceAccount:
                tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  data:
    - secretKey: SESSION_HASH_KEY
      remoteRef:
        key: CAPACITOR-NEXT-SESSION-HASH-KEY
    - secretKey: SESSION_BLOCK_KEY
      remoteRef:
        key: CAPACITOR-NEXT-SESSION-BLOCK-KEY
