apiVersion: v1
kind: Service
metadata:
  name: capacitor
  namespace: flux-system
spec:
  selector:
    app: capacitor-next
  ports:
    - name: http
      port: 9000
      targetPort: http
  type: ClusterIP
