apiVersion: v1
kind: Service
metadata:
  name: capacitor
  namespace: flux-system
spec:
  selector:
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: capacitor
  ports:
    - name: http
      port: 9000
      targetPort: http
  type: ClusterIP
