apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  timeout: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 83.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    grafana:
      envValueFrom:
        INFLUXDB_USERNAME:
          secretKeyRef:
            name: garmin-grafana-datasource
            key: INFLUXDB_USERNAME
        INFLUXDB_PASSWORD:
          secretKeyRef:
            name: garmin-grafana-datasource
            key: INFLUXDB_PASSWORD
      admin:
        existingSecret: grafana-admin-credentials
        userKey: admin-user
        passwordKey: admin-password
      persistence:
        enabled: true
        existingClaim: kube-prometheus-stack-grafana
        storageClassName: longhorn
        size: 2Gi
      service:
        type: ClusterIP
      additionalDataSources:
        - name: GarminInflux
          uid: DS_GARMIN_STATS
          type: influxdb
          access: proxy
          url: http://garmin-grafana-influxdb.garmin-grafana.svc.cluster.local:8086
          user: $__env{INFLUXDB_USERNAME}
          jsonData:
            version: InfluxQL
            dbName: GarminStats
            httpMethod: GET
          secureJsonData:
            password: $__env{INFLUXDB_PASSWORD}
      dashboards:
        garmin:
          garmin-grafana:
            gnetId: 23245
            revision: 2
            datasource:
              - name: DS_GARMIN_STATS
                value: GarminInflux

    prometheus:
      prometheusSpec:
        retention: 7d
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector: {}
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi

    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
