apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
        - name: pve-exporter
          image: prompve/prometheus-pve-exporter:3.10.0
          ports:
            - name: http
              containerPort: 9221
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/pve.yml
              subPath: pve.yml
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: config
          secret:
            secretName: pve-exporter-config
