apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: obsidian
data:
  config.yaml: |
    ingress:
      - hostname: obsidian.example.com
        service: http://obsidian.obsidian.svc.cluster.local:3000
      - service: http_status:404