apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: obsidian
data:
  config.yaml: |
    ingress:
      - hostname: obsidian.andriusdalgeda.com
        service: http://obsidian:3000
      - service: http_status:404