apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    metrics: 0.0.0.0:60123

    ingress:
      - hostname: obsidian.andriusdalgeda.com
        service: http://obsidian.obsidian.svc.cluster.local:3000
      - hostname: uptime.andriusdalgeda.com
        service: http://uptime-kuma.uptime-kuma.svc.cluster.local:3001
      - hostname: grafana.andriusdalgeda.com
        service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
      - hostname: prowlarr.andriusdalgeda.com
        service: http://prowlarr.prowlarr.svc.cluster.local:9696
      - hostname: cobalt.andriusdalgeda.com
        service: http://cobalt.cobalt.svc.cluster.local:9200
      - hostname: pdf.andriusdalgeda.com
        service: http://stirling-pdf.stirling-pdf.svc.cluster.local:8080
      - service: http_status:404
