apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      dnsConfig:
        dnsConfig:
          nameservers:
            - 1.1.1.1
            - 8.8.8.8
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 4500
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "home.andriusdalgeda.com"
          volumeMounts:
            - name: config
              mountPath: /app/config
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "1Gi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-config