apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared.yaml
  - uptime-kuma.yaml
  - obsidian.yaml
  - external-secrets.yaml
  - velero.yaml
  - longhorn-system.yaml
  - monitoring.yaml
  - prowlarr.yaml