apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared.yaml
  - uptime-kuma.yaml
  - obsidian.yaml
  - external-secrets.yaml
  - velero.yaml
  - longhorn-system.yaml
  - keda.yaml
  - monitoring.yaml
  - tailscale.yaml
  - prowlarr.yaml
  - stirling-pdf.yaml
  - azdo-agent.yaml
  - seerr.yaml
  - abs.yaml
  - forgejo.yaml
  - paperless.yaml
  - garmin-grafana.yaml
  - n8n.yaml
