apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: obsidian
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: git-credentials
    creationPolicy: Owner

  data:
    - secretKey: GIT-TOKEN
      remoteRef:
        key: GIT-TOKEN
