apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garmin-grafana-credentials
  namespace: garmin-grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure
    kind: ClusterSecretStore
  target:
    name: garmin-grafana-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        GARMINCONNECT_EMAIL: "{{ .GARMINCONNECT_EMAIL }}"
        GARMINCONNECT_BASE64_PASSWORD: "{{ .GARMINCONNECT_PASSWORD | b64enc }}"
        INFLUXDB_USERNAME: "{{ .INFLUXDB_USERNAME }}"
        INFLUXDB_PASSWORD: "{{ .INFLUXDB_PASSWORD }}"
        INFLUXDB_ADMIN_USER: "{{ .INFLUXDB_USERNAME }}"
        INFLUXDB_ADMIN_PASSWORD: "{{ .INFLUXDB_PASSWORD }}"
  data:
    - secretKey: GARMINCONNECT_EMAIL
      remoteRef:
        key: GARMINCONNECT-EMAIL
    - secretKey: GARMINCONNECT_PASSWORD
      remoteRef:
        key: GARMINCONNECT-PASSWORD
    - secretKey: INFLUXDB_USERNAME
      remoteRef:
        key: GARMIN-GRAFANA-INFLUXDB-USERNAME
    - secretKey: INFLUXDB_PASSWORD
      remoteRef:
        key: GARMIN-GRAFANA-INFLUXDB-PASSWORD
