apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: azure
  namespace: external-secrets
spec:
  provider:
    azurekv:
      tenantId: "970b9027-1298-479c-8ade-f396586b719c"
      vaultUrl: "https://kv-uks-primary-k8s.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret