apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-credential
    name: azure
    kind: ClusterSecretStore

  target:
    name: cloudflared-secret
    creationPolicy: Owner

  data:
    - secretKey: TUNNEL-TOKEN
      remoteRef:
        key: TUNNEL-TOKEN