apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure
spec:
  provider:
    azurekv:
      tenantId: "${AZURE_TENANT_ID}"
      vaultUrl: "${AZURE_KEYVAULT_URL}"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret
          namespace: external-secrets
