apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rreading-glasses-db
  namespace: rreading-glasses
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: rreading-glasses-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        POSTGRES_PASSWORD: '{{ index . "POSTGRES-PASSWORD" }}'

  data:
    - secretKey: POSTGRES-PASSWORD
      remoteRef:
        key: RREADING-GLASSES-POSTGRES-PASSWORD
