apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garmin-grafana-influxdb
  namespace: garmin-grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
