apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets
  - influxdb-pvc.yaml
  - tokens-pvc.yaml
  - influxdb-deployment.yaml
  - influxdb-service.yaml
  - garmin-deployment.yaml
