apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-tailscale
  namespace: n8n
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - n8n
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
