apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelfmark
  namespace: shelfmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shelfmark
  template:
    metadata:
      labels:
        app: shelfmark
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 1.1.1.1
          - 8.8.8.8
      containers:
        - name: shelfmark
          image: ghcr.io/calibrain/shelfmark:latest
          ports:
            - containerPort: 8084
          env:
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
            - name: ABB_ENABLED
              value: "true"
            - name: ABB_HOSTNAME
              value: "audiobookbay.lu"
            - name: AUDIOBOOK_LIBRARY_URL
              value: "http://abs.abs.svc.cluster.local:5000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: books
              mountPath: /books
            - name: downloads
              # advanced > remote path mapping - qbittorent to local
              mountPath: /home3/andriusdalgeda/qbittorrent/audiobooks
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: shelfmark-config
        - name: downloads
          persistentVolumeClaim:
            claimName: shelfmark-shared-downloads
        - name: books
          persistentVolumeClaim:
            claimName: shelfmark-books
