apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: shelfmark-shared-downloads
  namespace: longhorn-system
spec:
  accessMode: rwx
  dataLocality: disabled
  encrypted: false
  frontend: blockdev
  fromBackup: ""
  numberOfReplicas: 1
  size: "21474836480"
  staleReplicaTimeout: 30
