apiVersion: v1
kind: Service
metadata:
  name: shelfmark-shared-downloads-nfs
  namespace: longhorn-system
spec:
  selector:
    longhorn.io/volume: shelfmark-shared-downloads
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
  clusterIP: None
