apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-linkwarden
  namespace: glance
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure
    kind: ClusterSecretStore
  target:
    name: glance-linkwarden
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        LINKWARDEN_API_KEY: "{{ .LINKWARDEN_API_KEY }}"
  data:
    - secretKey: LINKWARDEN_API_KEY
      remoteRef:
        key: LINKWARDEN-API-KEY
