apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 10m
  chart:
    spec:
      chart: paperless-ngx
      version: 0.3.19
      sourceRef:
        kind: HelmRepository
        name: paperless
        namespace: flux-system
  install:
    createNamespace: true
  values:
    fullnameOverride: paperless
    config:
      url: https://paperless.taile6b0e8.ts.net
    env:
      TZ: UTC
      PAPERLESS_ALLOWED_HOSTS: paperless.andriusdalgeda.com,paperless.taile6b0e8.ts.net,paperless,10.0.1.30
      PAPERLESS_CORS_ALLOWED_HOSTS: https://paperless.andriusdalgeda.com,https://paperless.taile6b0e8.ts.net
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperless.andriusdalgeda.com,https://paperless.taile6b0e8.ts.net
      PAPERLESS_PROXY_SSL_HEADER: '["HTTP_X_FORWARDED_PROTO", "https"]'
      PAPERLESS_TRUSTED_PROXIES: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10,127.0.0.1
      PAPERLESS_USE_X_FORWARD_HOST: "true"
    service:
      port: 8888
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 15Gi
    postgresql:
      primary:
        persistence:
          storageClass: longhorn
          size: 8Gi
    valkey:
      dataStorage:
        className: longhorn
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: paperless
            patch: |
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false
