apiVersion: batch/v1
kind: CronJob
metadata:
  name: azdo-agent-health
  namespace: azdo-agent
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: check
              image: curlimages/curl:8.10.1
              imagePullPolicy: IfNotPresent
              env:
                - name: AZP_URL
                  valueFrom:
                    secretKeyRef:
                      name: azdo-agent-credentials
                      key: AZP-URL
                - name: AZP_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: azdo-agent-credentials
                      key: AZP-TOKEN
                - name: AZP_POOL
                  valueFrom:
                    secretKeyRef:
                      name: azdo-agent-credentials
                      key: AZP-POOL
                - name: KUMA_PUSH_URL
                  valueFrom:
                    secretKeyRef:
                      name: azdo-agent-monitoring
                      key: UPTIME-KUMA-AZDO-PUSH-URL
                - name: MIN_ONLINE_AGENTS
                  value: "1"
              command:
                - /bin/sh
                - -c
                - |
                  echo "Pushing to Uptime Kuma"
                  curl -s -o /dev/null "$KUMA_PUSH_URL"
