apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azdo-agent
  namespace: azdo-agent
spec:
  scaleTargetRef:
    name: azdo-agent
    envSourceContainerName: azdo-agent
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 300
  triggers:
    - type: azure-pipelines
      metadata:
        poolID: "9"
        targetPipelinesQueueLength: "1"
      authenticationRef:
        name: azdo-agent
