apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./uptime-kuma
  - ./cloudflared
  - ./obsidian
  - ./prowlarr
  - ./stirling-pdf
  - ./flaresolverr
  - ./azdo-agent
  - ./seerr
  - ./abs
