apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acr-pull
  namespace: azdo-agent
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: acr-pull-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ index . "registry" }}": {
                "username": "{{ index . "clientId" }}",
                "password": "{{ index . "clientSecret" }}",
                "auth": "{{ printf "%s:%s" (index . "clientId") (index . "clientSecret") | b64enc }}"
              }
            }
          }

  data:
    - secretKey: clientId
      remoteRef:
        key: ACR-CLIENT-ID

    - secretKey: clientSecret
      remoteRef:
        key: ACR-CLIENT-SECRET

    - secretKey: registry
      remoteRef:
        key: ACR-LOGIN-SERVER
