apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acr-pull
  namespace: azdo-agent
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: acr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .registry }}": {
                "username": "{{ .clientId }}",
                "password": "{{ .clientSecret }}",
                "auth": "{{ printf "%s:%s" .clientId .clientSecret | b64enc }}"
              }
            }
          }

  data:
    - secretKey: clientId
      remoteRef:
        key: ACR-CLIENT-ID

    - secretKey: clientSecret
      remoteRef:
        key: ACR-CLIENT-SECRET

    - secretKey: registry
      remoteRef:
        key: ACR-LOGIN-SERVER