apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azdo-agent-credentials
  namespace: azdo-agent
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: azdo-agent-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        AZP-URL: '{{ index . "AZP-URL" }}'
        AZP-TOKEN: '{{ index . "AZP-TOKEN" }}'
        AZP-POOL: '{{ index . "AZP-POOL" }}'

  data:
    - secretKey: AZP-URL
      remoteRef:
        key: AZP-URL

    - secretKey: AZP-TOKEN
      remoteRef:
        key: AZP-TOKEN

    - secretKey: AZP-POOL
      remoteRef:
        key: AZP-POOL
