apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azdo-agent-monitoring
  namespace: azdo-agent
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: azdo-agent-monitoring
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        UPTIME-KUMA-AZDO-PUSH-URL: '{{ index . "UPTIME-KUMA-AZDO-PUSH-URL" }}'

  data:
    - secretKey: UPTIME-KUMA-AZDO-PUSH-URL
      remoteRef:
        key: UPTIME-KUMA-AZDO-PUSH-URL
