apiVersion: apps/v1
kind: Deployment
metadata:
  name: rreading-glasses
  namespace: rreading-glasses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rreading-glasses
  template:
    metadata:
      labels:
        app: rreading-glasses
    spec:
      containers:
        - name: rreading-glasses
          image: blampe/rreading-glasses:latest
          command:
            - /main
            - serve
          args:
            - --upstream=www.goodreads.com
            - --verbose
          ports:
            - containerPort: 8788
          env:
            - name: POSTGRES_HOST
              value: rreading-glasses-db
            - name: POSTGRES_DATABASE
              value: rreading-glasses
            - name: POSTGRES_USER
              value: rreading-glasses
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rreading-glasses-db
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8788
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /
              port: 8788
            initialDelaySeconds: 30
            periodSeconds: 30
