apiVersion: v1
kind: Service
metadata:
  name: rreading-glasses-db
  namespace: rreading-glasses
  labels:
    app: rreading-glasses-db
spec:
  selector:
    app: rreading-glasses-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rreading-glasses-db
  namespace: rreading-glasses
spec:
  serviceName: rreading-glasses-db
  replicas: 1
  selector:
    matchLabels:
      app: rreading-glasses-db
  template:
    metadata:
      labels:
        app: rreading-glasses-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: rreading-glasses
            - name: POSTGRES_USER
              value: rreading-glasses
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rreading-glasses-db
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - rreading-glasses
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - rreading-glasses
            initialDelaySeconds: 30
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
