apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/apps
  prune: true
  dependsOn:
    - name: external-secrets-resources
    - name: longhorn
    - name: metrics-server
    - name: keda
    - name: monitoring
  postBuild:
    substituteFrom:
      - kind: Secret
        name: azdo-image-repository
  sourceRef:
    kind: GitRepository
    name: flux-system
