apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobalt
  namespace: cobalt
  labels:
    app: cobalt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobalt
  template:
    metadata:
      labels:
        app: cobalt
    spec:
      containers:
        - name: cobalt
          image: ghcr.io/imputnet/cobalt:11
          ports:
            - containerPort: 9000
          env:
            - name: API_URL
              value: "https://cobalt.andriusdalgeda.com/"
          securityContext:
            readOnlyRootFilesystem: true
      restartPolicy: Always
