apiVersion: v1
kind: Service
metadata:
  name: cobalt
  namespace: cobalt
  labels:
    app: cobalt
spec:
  selector:
    app: cobalt
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  type: ClusterIP
