apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure
    kind: ClusterSecretStore

  target:
    name: tailscale-operator-oauth
    creationPolicy: Owner

  data:
    - secretKey: clientId
      remoteRef:
        key: TAILSCALE-OAUTH-CLIENT-ID
    - secretKey: clientSecret
      remoteRef:
        key: TAILSCALE-OAUTH-CLIENT-SECRET
